import Head from 'next/head';
import Navbar from '../components/navbar/Navbar';
import styles from '../styles/Home.module.css';
import Header from '../components/header/Header';
import Services from '../components/services/Services';
import Destinations from '../components/destinations/Destinations';
import Book from '../components/book/Book';
import Testimonials from '../components/testimonials/Testimonials';
import Sponsors from '../components/sponsors/Sponsors';
import Subscribe from '../components/subscribe/Subscribe';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Navbar />
        <Header />
        <Services />
        <Destinations />
        <Book />
        <Testimonials />
        <Sponsors />
        <Subscribe />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
