import Head from 'next/head';
import Header from '../components/header/Header';
import Navbar from '../components/navbar/Navbar';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Navbar />
        <Header />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
